### ISSUE TITLE
Keyboard Shortcut

### ISSUE THREAD

**Issue by FPVian** [Falki-git/I-Wish-They-Made-UI-Customizable#3]
Would it be possible to add a keyboard shortcut for the FUBAR button? Or to bring up the mod UI? 

When switching back and forth between triple screens my ui elements go off the screen and I can't access the mod menu anymore.

Also can you tag this as being compatible with game version 0.2.0?

**Comment by Falki-git** [comment]
Sure, I could add a keybind that triggers the UI, that's a good idea.

**Comment by Falki-git** [comment]
Solved in https://github.com/Falki-git/I-Wish-They-Made-UI-Customizable/pull/4

**Comment by FPVian** [comment]
Thank you!
